codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: false

coverage:
  precision: 2
  round: down
  range: "40...90"
  status:
    project:
      default:
        target: 50%
        threshold: 5%
    patch:
      default:
        target: 50%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
